### ISSUE TITLE
Share the email address for Slack invitation requests to „raise any questions...on the #dps_tech_team channel“

### ISSUE THREAD

**Issue by deduper** [ministryofjustice/hmpps-auth#871]
[_This repo's README_](https://github.com/ministryofjustice/hmpps-auth) says:

> _...Please raise any questions on the server on the #dps_tech_team channel in slack - https://mojdt.slack.com/archives/CK0QLCQ1G..._

The [_MOJ Digital &amp; Technology on Slack signup page_](https://mojdt.slack.com/signup/#) says:

> _Don’t have an email address from one of those domains?_
> _Contact the workspace administrator at MOJ Digital & Technology for an invitation..._

![mojdt slack channel signup 377 x 847](https://user-images.githubusercontent.com/21254896/116866772-80254800-abfb-11eb-98c6-2760968ecbb0.png)

Please reply with the email address that Slack channel invitation requests need to be sent to?

TIA.

**Comment by deduper** [comment]
### What have you tried so far?

Since [_the MOJ Digital & Technology on Slack signup page_](https://mojdt.slack.com/signup/#): says, „_Contact the workspace administrator..._“, I tried guessing what the invitation request email address(_es_) might be:

1. administrator@justice.gov.uk
2. administrator@digital.justice.gov.uk

This is the Mail Delivery System reply I got back a few minutes after I tried sending requests to both of those:

```
...
Subject: Mail delivery failed: returning message to sender
...

This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

administrator@justice.gov.uk
host justice-gov-uk.mail.protection.outlook.com [104.47.10.36]
SMTP error from remote mail server after RCPT TO::
550 5.4.1 Recipient address rejected: Access denied. AS(201806281) [DB5EUR03FT027.eop-EUR03.prod.protection.outlook.com]
administrator@digital.justice.gov.uk
host aspmx.l.google.com [2a00:1450:400c:c0b::1a]
SMTP error from remote mail server after RCPT TO::
550-5.1.1 The email account that you tried to reach does not exist. Please try
550-5.1.1 double-checking the recipient's email address for typos or
550-5.1.1 unnecessary spaces. Learn more at
550 5.1.1 support.google.com/mail/?p=NoSuchUser t3si12668341wrv.560 - gsmtp
```

**Comment by petergphillips** [comment]
Thanks very much for raising the issue.  I've now updated the README.md to ask people to raise any questions / issues here and also added a security policy as realised it was missing.
