### ISSUE TITLE
Describe hmpps-auth's OAuth 2.0 Client Registration process in more detail

### ISSUE THREAD

**Issue by deduper** [ministryofjustice/hmpps-auth#882]
I am on a non-ministryofjustice team. Our project will be an OAuth 2.0 client to one of the ministryofjustice's OAuth 2.0 resource servers. A resource server that is protected by hmpps-auth.

My job is to report to my team, the answer to this question:

* _What is hmpps-auth's explicit step-by-step process for OAuth 2.0 client registration?_

[_The IETF RFC for OAuth 2.0_](https://tools.ietf.org/html/rfc6749#section-2) talks about registration of an actor in the client role: 

>> #### _2. Client Registration_
>> 
>>    _Before initiating the protocol, the client registers with the
>>    authorization server.  The means through which the client registers
>>    with the authorization server are beyond the scope of this
>>    specification but typically involve end-user interaction with an HTML
>>    registration form._
>> 
>>    _Client registration does not require a direct interaction between the
>>    client and the authorization server.  When supported by the
>>    authorization server, registration can rely on other means for
>>    establishing trust and obtaining the required client properties
>>    (e.g., redirection URI, client type).  For example, registration can
>>    be accomplished using a self-issued or third-party-issued assertion,
>>    or by the authorization server performing client discovery using a
>>    trusted channel._

[_The hmpps-auth project's README_](https://github.com/ministryofjustice/hmpps-auth) says:

> „_...For dev (t3) you will need client credentials to connect, *ask in #dps_tech_team to get setup*..._“

Since I'm not a ministryofjustice employee [_I don't have access to that Slack channel_](https://github.com/ministryofjustice/hmpps-auth/issues/871).

Please reply here with a list of  all the steps hmpss-auth requires for OAuth 2.0 client registration? More specifically:

1. _How do we get a client id?_
2. _How do we get a client secret?_
3. _What are the specific hmpss-auth URIs (_for t2, t3, pre-prod, prod, etc._) that we would configure in our client application?_
4. _Any other steps I haven't listed that are also required?_

**Comment by petergphillips** [comment]
Morning.  We do grant third parties access to our slack organisation so that they can ask questions, get client information etc.

The first step would be to find out what organisation you work for and what team in the MoJ you are interacting with.  They will either find a way for you to communicate directly with us, or we would liaise with them to grant you access.

We can then provide more specific information on getting you integrated, accounts set up on our development system (t3) etc. once we have established official contact.
